### ISSUE TITLE
Beach boxing gloves

### ISSUE THREAD

**Issue by Natesky9** [gc/oldschooljs#85]
in oldschooljs/src/data/items/
Item ids: 11705,11706 are duplicate name
messes with discord bot, suggest alternatives:

11705: Beach boxing gloves (yellow)
11706: Beach boxing gloves (pink)

**Comment by gc** [comment]
This is a problem in the bot itself.

**Comment by Natesky9** [comment]
It's an issue because the bot looks up the item id from name, and both names "Beach boxing gloves" only return 11705. What do you suggest the github for the bot to do?

**Comment by gc** [comment]
You basically just said it yourself, the bot looks it up by name, instead of getting the first item with the inputted name, it should get all with that name and handle it in some way, for example 2 ways you can handle it: pick which one to use based on whether the user has that item or not, or ask the user themselves with a prompt which item they want (using the wiki name to differentiate them). Its a bug in the bots code: https://github.com/gc/oldschoolbot/issues/156
