### ISSUE TITLE
[Question] GWD Bosses drop tables

### ISSUE THREAD

**Issue by koigejaoks** [gc/oldschooljs#91]
How did you calculate the coin weight in gwd bosses drop tables. For example for General Graardor it's 28 [here](https://github.com/gc/oldschooljs/blob/master/src/simulation/monsters/gwd/GeneralGraardor.ts#L63). In the wiki I see it's `(31.7 + 1.25)/127`? What are the steps to get 28 as the weight for coins?

**Comment by Maurits825** [comment]
Im not the one who coded that drop table, but its based on the wiki displaying the overall chance of getting those amount of coins from multiple tables. There is a [note](https://oldschool.runescape.wiki/w/General_Graardor#cite_note-5) on the wiki saying it comes from multiple tables. So the 31.7/127 is a sum of the chances of getting coins from the main table, GDT and RDT. Since the GDT and RDT already have their own [subtables ](https://github.com/gc/oldschooljs/blob/master/src/simulation/subtables/GWRareDropTable.ts) with coins, you need to substract those chances from 31.7/127. The coin weight from GDT and RDT are around 3.7/127, 31.7-3.7=28. The 1.25/127 coins chance is included [here](https://github.com/gc/oldschooljs/blob/114f191407559bde6316c7f4703338764741520e/src/simulation/monsters/gwd/GeneralGraardor.ts#L43). Hope that makes sense!

**Comment by koigejaoks** [comment]
I see. I'm trying to make sense of how this `3.7/127` came to be. I tried calculating and summing up the chance of getting coins from GDT and RDT but I can't get seem to get 3.7/127 as the sum there. 
Do you happen to have a detailed series of steps how to calculate that?
Maybe @gc could shed some light on this as well 🙏

**Comment by Maurits825** [comment]
You get 3.7/127 by summing up all the ways of getting coins from the GDT and RDT. The roll to get on the GDT is 2/127 and the coin drop in GTD is 63/128, so to start: `(2/127) * (63/128)`. In the GDT, you can also roll the mega-rare table, which also has coins: `(2/127) * (1/128) * (113/128)`. So in total for GDT:   `sum = ((2/127) * (63/128)) + ((2/127) * (1/128) * (113/128)) =~ 0.0079`. That is `0.0079/1` so multiply by 127 to get aprox `1/127`. You use the same logic for the RDT, which will results in `2.7/127`, total of `3.7/127`. The RDT has 4 total paths to coins drop:
- RDT - coins
- RDT - GTD - coins
- RDT - GTD - mega - coins
- RDT - mega - coins

**Comment by koigejaoks** [comment]
What do you mean by `That is 0.0079/1 so multiply by 127 to get aprox 1/127`. `0.0079/1 * 127` is `1/127`?

**Comment by Maurits825** [comment]
`(0.0079/1) * (127/127) = (0.0079*127)/(1*127) = 1/127`
Since `0.0079` is the chance out of 1, we want to convert it to a chance of of 127, which is done by multiplying by `127/127`

**Comment by koigejaoks** [comment]
I finally get it now 😄. I indeed adds up. I can understand why the weight of coins is 33 in the main table of gwd bosses. Thanks for the explanation!

**Comment by gc** [comment]
Cool. I think another contributor wrote this particular code (either alexsuperfly or wyattos)
